[package]
name = "rejects"
version = "0.1.0"
authors = ["Adam P. Regasz-Rethy <rethy.spud@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
